### ISSUE TITLE
Does this extension works for VSCode remote SSH?

### ISSUE THREAD

**Issue by Jack-Works** [andrewbranch/vscode-tsserver-debug#2]

**Comment by andrewbranch** [comment]
Oops, for some reason I wasn’t watching this repo. I don’t know the answer to this question, let me know if you find out 😁

**Comment by Jack-Works** [comment]
I don't remember if it is working but I have set up my develop process of ts lang server successfully

**Comment by andrewbranch** [comment]
The world may never know
